[project]
name = "v8vision"
version = "0.1.0"
description = "Live NASCAR Dashboard"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[project.scripts]
v8vision = "v8vision:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyinstaller>=6.22.2",
]
